services:
  - type: web
    runtime: python
    name: flask-backend
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    plan: free
    envVars:
      - key: GOOGLE_API_KEY
        sync: false
